const roles = ['user', 'instructor', 'admin'];

const roleRights = new Map();
roleRights.set(roles[0], [
  'optional.get',
  'user.get',
  'user.update',
  'course.gets-for-moodle',
  'course.gets',
  'course.update',
  'history.update',
  'history.delete',
  'history.create',
  'history.gets',
  'history.get',
  'comment.create',
  'comment.update',
]);
roleRights.set(roles[1], [
  'optional.get',
  'user.get',
  'user.update',
  'course.update',
  'course.create',
  'course.delete',
  'course.gets',
  'course.get',
  'comment.delete',
  'comment.create',
  'comment.update',
  'history.update',
  'history.delete',
  'history.create',
  'history.gets',
  'history.get',
  'section.create',
  'section.update',
  'section.delete',
  'section.get',
  'section.gets',
  'lecture.create',
  'lecture.update',
  'lecture.delete',
  'lecture.gets',
  'lecture.get',
]);
roleRights.set(roles[2], [
  'optional.get',
  'user.gets',
  'user.get',
  'user.update',
  'user.create',
  'user.delete',
  'category.update',
  'category.create',
  'category.delete',
  'category.gets',
  'category.get',
  'sub-category.update',
  'sub-category.create',
  'sub-category.delete',
  'sub-category.gets',
  'sub-category.get',
  'comment.delete',
  'comment.gets',
  'comment.get',
  'course.update',
  'course.delete',
  'course.gets',
]);

module.exports = {
  roles,
  roleRights,
};
